### PR TITLE
Fix cards

### LINKED ISSUE #10: Include card images in world overview
We could include images of sites and denizens on the world overview. All the cards are available at https://oathcards.seiyria.com/ and should be accessible with some simple formatting,

    cardURL = "https://oathcards.seiyria.com/assets/cards/" + cardName + ".webp"

An elegant solution might be to only display the picture when text is hovered over, like this: https://jsfiddle.net/1cxjf0nq/ .

It could even be expanded to some kind of tag in the chronicle for whenever a card is mentioned.

I am going to wait with working on this until the current refactoring is done.

### PR DESCRIPTION
**Pull request by alexrutar**
Here's a starting point to include the site images. I've downloaded all the card images from the suggested location, and also fixed some naming issues.

### CODE REVIEW

**Comment by alexrutar** [comment]
There also seems to be an error in the parser, since the vision naming is wrong: the visions [here](https://github.com/alexrutar/helichrysum/blob/9259ff57ce07969fdeda207e5e074c78183a3c12/assets/js/cards.js#L216) should be Faith, Rebellion, Sanctuary, and Conquest

**Comment by alexrutar** [comment]
The savestring from your other game would be useful for testing. For convenience I'm leaving it here:
```
030303000613The First Chronicle3A0200012345133111E910CE2AE3000AE5FF07FFFFDD12FFFFFF0CD0DCFF23FFFFFF08C770FF36847714AF870828D4D66E047C8FD2D3059B09AAD5248CC00C1C335D32302BA4181E590B0E131D3D2D9C379DC517AB2C349E011B167F201E252758121F290D0F350015075E220203061A212319882E267D2F901067B80FEBDFE8EDE7E1DBECE2EAE6DEE0DAE4002004Bock
```

**Comment by AndBM** [comment]
The Tribunal was missing from the cards folder and your "all cards" list. Not sure to check for other missing cards. How did you scrape the cards?

**Comment by AndBM** [comment]
Everything should be ready - feel free to take a last look for missing cards and check that the site compiles properly online (offline is fine but online hasn't compiled yet). Then we should merge.

**Comment by alexrutar** [comment]
I originally had pulled the card names from the outdated card lookup file, and then infilled anything I could see missing. I've now pulled all the card names from `sites.js` and `cards.js`, along with a couple additional modifications (visions, banners, etc.). and I checked that every name in that file was properly downloaded. Funnily enough, "The Tribunal" was the only one that was missing!

I've also touched up the script a bit, too. And the file `all.txt` now contains a proper list of all the cards (sorted by alphabetical order).

**Comment by alexrutar** [comment]
I just wonder if the links should link to the original source, instead of just to the root of the document? It might be a bit nicer.

Or we could remove the links entirely, and just use a `<span>` element with a mouseover property.

**Comment by AndBM** [comment]
What exactly do you mean link to the original source? From the other website? For the span method, feel free to change the implementation.

**Comment by AndBM** [comment]
I see what you mean now. I think this is the best way to also make it work on mobile, where you have to actually click it to get the hover image. I have changed it so that it does not send you to the top of the page when you click, instead it send you nowhere.

**Comment by alexrutar** [comment]
I tried implementing the span method, which worked well on my computer, but resulted in weird selection behaviour on mobile which I could not fix. I've reverted it for now and I'll see if I can make it work tomorrow.

**Pull request merged**
